//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System_aks_vn.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System_aks_vn.Resources.Languages.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string deviceDefaultHistory {
            get {
                return ResourceManager.GetString("deviceDefaultHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        internal static string deviceDefaultNow {
            get {
                return ResourceManager.GetString("deviceDefaultNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string deviceHistory {
            get {
                return ResourceManager.GetString("deviceHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string devicehistorydetail {
            get {
                return ResourceManager.GetString("devicehistorydetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string deviceSetting {
            get {
                return ResourceManager.GetString("deviceSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the alarm phone numbers here.
        /// </summary>
        internal static string deviceSettingCallTitle {
            get {
                return ResourceManager.GetString("deviceSettingCallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the alarm phone numbers here.
        /// </summary>
        internal static string deviceSettingSmsTitle {
            get {
                return ResourceManager.GetString("deviceSettingSmsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string deviceSettingSubmitBtn {
            get {
                return ResourceManager.GetString("deviceSettingSubmitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device control.
        /// </summary>
        internal static string devicesettingTitle {
            get {
                return ResourceManager.GetString("devicesettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Status.
        /// </summary>
        internal static string deviceTitle {
            get {
                return ResourceManager.GetString("deviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Device.
        /// </summary>
        internal static string homeDevice {
            get {
                return ResourceManager.GetString("homeDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string homeMenu {
            get {
                return ResourceManager.GetString("homeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string loginPasswordPlaceHold {
            get {
                return ResourceManager.GetString("loginPasswordPlaceHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string loginSaveInfo {
            get {
                return ResourceManager.GetString("loginSaveInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the owner server name.
        /// </summary>
        internal static string loginServer {
            get {
                return ResourceManager.GetString("loginServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string loginServerPlaceHold {
            get {
                return ResourceManager.GetString("loginServerPlaceHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string loginSubmitBtn {
            get {
                return ResourceManager.GetString("loginSubmitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string loginTitle {
            get {
                return ResourceManager.GetString("loginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter you account information.
        /// </summary>
        internal static string loginUserName {
            get {
                return ResourceManager.GetString("loginUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string loginUserNamePlaceHold {
            get {
                return ResourceManager.GetString("loginUserNamePlaceHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string settingActionDevice {
            get {
                return ResourceManager.GetString("settingActionDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your device list.
        /// </summary>
        internal static string settingActionDeviceD {
            get {
                return ResourceManager.GetString("settingActionDeviceD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use.
        /// </summary>
        internal static string settingActionGuide {
            get {
                return ResourceManager.GetString("settingActionGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions for using application features.
        /// </summary>
        internal static string settingActionGuideD {
            get {
                return ResourceManager.GetString("settingActionGuideD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password with a new one.
        /// </summary>
        internal static string settingActionPasswordD {
            get {
                return ResourceManager.GetString("settingActionPasswordD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string settingActionProfile {
            get {
                return ResourceManager.GetString("settingActionProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure user information.
        /// </summary>
        internal static string settingActionProfileD {
            get {
                return ResourceManager.GetString("settingActionProfileD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string settingActionQuestion {
            get {
                return ResourceManager.GetString("settingActionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of frequently asked questions.
        /// </summary>
        internal static string settingActionQuestionD {
            get {
                return ResourceManager.GetString("settingActionQuestionD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staffs.
        /// </summary>
        internal static string settingActionStaff {
            get {
                return ResourceManager.GetString("settingActionStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your list of users.
        /// </summary>
        internal static string settingActionStaffD {
            get {
                return ResourceManager.GetString("settingActionStaffD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        internal static string settingCall {
            get {
                return ResourceManager.GetString("settingCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set call number for device.
        /// </summary>
        internal static string settingCallDes {
            get {
                return ResourceManager.GetString("settingCallDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string settingConfirmPassword {
            get {
                return ResourceManager.GetString("settingConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract to AKS.
        /// </summary>
        internal static string settingContract {
            get {
                return ResourceManager.GetString("settingContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management and setup.
        /// </summary>
        internal static string settingFrameManager {
            get {
                return ResourceManager.GetString("settingFrameManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Information.
        /// </summary>
        internal static string settingFrameSupport {
            get {
                return ResourceManager.GetString("settingFrameSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string settingHome {
            get {
                return ResourceManager.GetString("settingHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string settingLogout {
            get {
                return ResourceManager.GetString("settingLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter and confirm your new password.
        /// </summary>
        internal static string settingNewPassword {
            get {
                return ResourceManager.GetString("settingNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string settingNewPasswordPlaceHold {
            get {
                return ResourceManager.GetString("settingNewPasswordPlaceHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your current password.
        /// </summary>
        internal static string settingOldPassword {
            get {
                return ResourceManager.GetString("settingOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string settingOldPasswordPlaceHold {
            get {
                return ResourceManager.GetString("settingOldPasswordPlaceHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string settingProfile {
            get {
                return ResourceManager.GetString("settingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string settingSchedule {
            get {
                return ResourceManager.GetString("settingSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up a configuration schedule for the device.
        /// </summary>
        internal static string settingScheduleDes {
            get {
                return ResourceManager.GetString("settingScheduleDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        internal static string settingSms {
            get {
                return ResourceManager.GetString("settingSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set sms number for device.
        /// </summary>
        internal static string settingSmsDes {
            get {
                return ResourceManager.GetString("settingSmsDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string settingSubmitBtn {
            get {
                return ResourceManager.GetString("settingSubmitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string settingTitle {
            get {
                return ResourceManager.GetString("settingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Version used.
        /// </summary>
        internal static string settingVersion {
            get {
                return ResourceManager.GetString("settingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string shellHome {
            get {
                return ResourceManager.GetString("shellHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string shellSetting {
            get {
                return ResourceManager.GetString("shellSetting", resourceCulture);
            }
        }
    }
}
